"""Generated by python/scripts/sync_data.py. Do not edit by hand."""

#: Package version (independent of the bundled dataset version).
__version__ = "0.12.0"

#: Release version of the bundled calendar data.
DATA_VERSION = "11.0.0"

#: calendar-project commit the data was generated from.
DATA_GIT_SHA = "3765bcb10d3ebcb7cfc338bcebf94505af25ec1e"

#: Date the data was generated.
DATA_GENERATION_DATE = "2026-02-16"
