"""Generated by python/scripts/sync_data.py. Do not edit by hand."""

#: Package version (independent of the bundled dataset version).
__version__ = "0.12.0"

#: Release version of the bundled calendar data.
DATA_VERSION = "12.0.0"

#: calendar-project commit the data was generated from.
DATA_GIT_SHA = "adf8dd99893301852aa3daccfb7f0caee22859f3"

#: Date the data was generated.
DATA_GENERATION_DATE = "2026-09-14"
